### ISSUE TITLE
Get rid of options page while playing

### ISSUE THREAD

**Issue by RRothfeld** [Redfielder/NeverEver#3]
Can we get rid of the options page when playing?

Adding players will be on play screen, NSFW is easy to inclide with a toggle button, and the categories could be on a dropdown.

What do you think?

or at least make the cateories in a hidden div and show it on button press, but not in a seperate page?

**Comment by GeorgiosGoulos** [comment]
If we do that we'd probably have to use a "make changes" button in the same page and that would be kinda ugly (2 buttons that "redirect" to the same page). If we do it using AJAX, we'd then have to pick a new statement as well since the new category list might nott include the existing one so it's almost like we're refreshing the page. I think it would be kinda messy to have all that stuff there unless you guys can come up with a nice way of displaying and manipulating them

**Comment by RRothfeld** [comment]
okay. then options page will stay for the moment
